apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/srikanth597/argocd-demo.git'
    path: argo-cd
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true